"""added relationship round 2

Revision ID: fdd063b8d23d
Revises: 11a74b354e74
Create Date: 2021-09-30 21:01:00.165868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd063b8d23d'
down_revision = '11a74b354e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
